### ISSUE TITLE
ERROR: missing APP0 marker, aborting! Using jpegli

### ISSUE THREAD

**Issue by ampaze** [ImageProcessing-ElectronicPublications/jpeg-recompress#7]
I tried to use jpeg-recompress with `mozjpeg` and `jpegli` to compare the achievable file sizes.

```bash
#export LD_PRELOAD=/usr/lib/libjpeg.moz.so
export LD_PRELOAD=/usr/lib/libjpeg.jpegli.so
jpeg-recompress -l 10 --min 10 -t 0.8 -a -m ms-ssim test.jpg test2.jpg
```

When using `jpegli` in that way I get the error
> New size is 82% of original (saved 145 kb)
> ERROR: missing APP0 marker, aborting!

when the file is going to be written to disk.

I used `libjpeg62-turbo-dev` instead of `libjpeg8-dev` as the latter is not available for Debian anymore. Could this be an issue?
On the other hand, `mozjpeg` is working and was also compiled with `libjpeg62-turbo-dev`. The `cjpeg` tool is also working fine with `jpegli`.

Any ideas?

**Comment by zvezdochiot** [comment]
Not.
